
service: example-aws-lambda-serverless

# app and org for use with dashboard.serverless.com
app: test-app
org: saurav741

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    APP_ID: ${param:APP_ID}
    PRIVATE_KEY: ${param:PRIVATE_KEY}
    WEBHOOK_SECRET: ${param:WEBHOOK_SECRET}
    NODE_ENV: production
    LOG_LEVEL: debug

functions:
  webhooks:
    handler: handler.webhooks
    events:
      - httpApi:
          path: /api/github/webhooks
          method: post